apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: discord
  name: stryder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stryder
  template:
    metadata:
      labels:
        app: stryder
    spec:
      containers:
        - name: stryder
          image: ghcr.io/darbiadev/stryder:main
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: stryder-secrets
      imagePullSecrets:
        - name: dockerconfigjson-github
